content/doc/integrations.md
This just adds a link to the integration page with the saltstack formula people can use.
=> Add link to saltstack formula

content/doc/aptly/repo/include.md
* Fix typo in Json example
* Consistency of comma use.
=> Typo in repo/include/ example

layouts/download/single.html
This pull request updates the links to the various Debian and Ubuntu packages for aptly available in the official repositories.
current aptly versions:
Debian:
*   jessie (stable) 0.8-3
*   stretch (testing) 0.9.7-1
*   sid (unstable) 0.9.7-1
Ubuntu:
*    xenial (16.04LTS) 0.9.6-1
*    yakkety (16.10) 0.9.7-1
*    zesty 0.9.7-1
=> Update links to Debian / Ubuntu packages for aptly

content/doc/aptly/publish/show.md, content/doc/aptly/snapshot/show.md
Documentation adjustment for print sources changes as per PR https://github.com/smira/aptly/pull/472
=> Represent new sources details for snapshot and published repositories

content/doc/api.md
take security relevant notes out of the notes list and give them their own
section. mention that socket listening would be preferred due to tighter
access control and how to start aptly with a socket.
(also changed ordered list to numerate via 1. so one can freely remove/add
stuff without getting OCD triggered on making sure the numering is
consistent ;-))
=> add more documentation on api security + add mentioniong of socket listen

content/doc/aptly/mirror/update.md
Corresponding to https://github.com/smira/aptly/pull/520
=> Added command line option -skip-existing-packages to the mirror update description.

content/doc/integrations.md
[aptly-api-client](https://github.com/gopythongo/aptly-api-client/) is a pythonic low-level abstraction over the aptly API.
=> Add my Python API client library to the integrations page

content/doc/api/publish.md
Apparently, the options didn't get documented when they were added to aptly 1.1
=> document new publish api properties NotAutomatic and ButAutomaticUpgrades

content/doc/api/publish.md
follow up to 395d7440296912813022ec6e5cfa8de47ffe417e where I only added
them to the object properties while in fact they are also parameters for
the actual publish call (which is where the properties are set)
:cry:
=> also document NotAutomatic and ButAutomaticUpgrades as publish params

content/doc/aptly/mirror/edit.md
Adds documentation for https://github.com/smira/aptly/pull/677/
=> Document mirror edit flags for editing archive url

content/doc/api/publish.md
This extens the document to cover the already existing AcquireByHash on switch/update *and* the full coverage from https://github.com/smira/aptly/pull/696 (pending)
=> document new AcquireByHash in publish API

content/doc/api/publish.md
Already send pull, which is accepted, but don't get why there is two repos and doc page still have this typo
https://github.com/smira/aptly-dev.github.io/pull/2
=> fix publish api typo

content/doc/api.md, content/doc/aptly/serve.md
They got mixed up with `aptly serve` docs.
See smira/aptly#700
=> Fix `aptly api serve` docs

content/doc/feature/pgp-providers.md
we currently only support gpg1 and have an unknown host of compatibility
issues with gpg2. advise that users make sure the gpg1 packages are
installed to use aptly.
(this could also go into the FAQ, but seeing as we have a specific feature page we might as well document this defect there)
relates to aptly-dev/aptly/issues/657
=> document pgp limitation about only supporting gpg1

layouts/index.html, layouts/partials/footer.html
This section was mentioning features we're most probably won't be
working in the nearest future.
Also update footer copyright.
=> Remove 'upcoming features' section

.travis.yml, Makefile
CI can't get and install Hugo packages: [Build #151](https://travis-ci.org/github/aptly-dev/www.aptly.info/builds/766251345)
Hugo >= 0.81.0 only builds with >= Go 1.16.
github.com/spf13/hugo redirects to github.com/gohugoio/hugo, but Go 1.16 don't allow redirects by default:
```
go: downloading github.com/spf13/hugo v0.82.0
go get: github.com/spf13/hugo@v0.47.1 updating to
github.com/spf13/hugo@v0.82.0: parsing go.mod:
module declares its path as: github.com/gohugoio/hugo
but was required as: github.com/spf13/hugo
1
```
So we need to update Hugo URL also.
=> Update Hugo build: requires Go >= 1.16

config.toml
Enable HTML rendering to display code blocks in Tutorials.
Fixes #82
=> Enable HTML rendering to display code blocks

content/doc/aptly/mirror/create.md
Fix a typo: Prirority => Priority.
=> Fix a typo: Prirority => Priority

content/doc/integrations.md
[OpenAPT](https://openapt.org) is a tool developed by [ALLOcloud](https://allocloud.com) team. It's a file format which allows user to describe APT repositories specifications with a JSON/YAML file. It's also an implementation in Python which automates aptly based on these specifications.
The goal is to document the layout of APT repositories and automate their build with aptly commands. Flow and keywords are inspired by core entities from aptly.
=> Document OpenAPT solution in integrations

content/doc/aptly/publish/switch.md
Fix type: s/snould/should
Signed-off-by: Ariel D'Alessandro <ariel.dalessandro@collabora.com>
=> content: publish: Fix typo on switch docs

content/doc/feature/s3.md
This new configuration value was added in 1.5.0 with this PR:
- https://github.com/aptly-dev/aptly/pull/1087
=> S3: add docs for `acl: none` value

content/doc/api/repos.md
The link to aptly repo changed, or was wrong. Update it to point to the
`aptly repo include` command documentation as intended.
=> Fix link from API repos to aptly repo include

layouts/download/single.html
Fixes https://github.com/aptly-dev/aptly/issues/1098
Tested in Ubuntu 20.04, 22.04, 24.04 container
=> Update installation steps for Ubuntu 24

.github/workflows/gh-pages.yml, config.toml
Fixes #92 
Fixes a deprecated config option Hugo has, and pins Hugo to 0.139.0 so we don't unintentionally hit this again.
=> Fix hugo author deprecation

content/doc/integrations.md
Hetzner Cloud uses aptly internally and published its role to the public which they use. It supports idempotent repository and mirror configuration.
=> integrations: add ansible role by hetzner cloud
