aptly-dev/www.aptly.info

content/doc/aptly/repo/search.md

I think the name parameter description is incorrect.
May result from bad c/p.

Fix name parameter description

---

content/doc/feature/s3.md

Small update to the s3 feature.

APT S3 transport update

---

content/doc/why.md

The word "but" suggests me that other tools are UNable to create partial mirrors. Is that what you mean?

Update why.md about partial mirrors

---

static/css/styles.css
static/css/styles.less

Just a small things. Noticed this earlier when reading through the docs.

Fetching fonts through https instead of http

---

layouts/partials/header.html

Fix wording

---

content/doc/aptly/mirror/update.md

PR https://github.com/smira/aptly/pull/463 already pulled.

Added mirror update -max-tries flag documentation

---

content/doc/api/misc.md
content/doc/aptly/graph.md

Documentation on graph's new layout parameter according to PR https://github.com/smira/aptly/pull/475

Add documentation on graph parameter 'layout'

---

content/doc/aptly/repo/create.md

Add `aptly repo create ... from snapshot`

---

content/doc/aptly/flags.md
content/doc/aptly/mirror/create.md
content/doc/aptly/mirror/edit.md
content/doc/aptly/mirror/search.md
content/doc/aptly/repo/copy.md
content/doc/aptly/repo/import.md
content/doc/aptly/repo/move.md
content/doc/aptly/repo/search.md
content/doc/aptly/snapshot/filter.md
content/doc/aptly/snapshot/pull.md
content/doc/aptly/snapshot/search.md
content/doc/configuration.md
content/doc/feature/dependencies.md
layouts/shortcodes/version.html

This also adds docs for new option for detailed
dependency resolving, and adds new "version" badge to
mark features per each new aptly version.

Add documentation on dependency resolving

---

content/doc/configuration.md

Document new `skipLegacyPool` config option

---

content/doc/aptly/publish/repo.md
content/doc/aptly/publish/snapshot.md

Updated documentation for https://github.com/smira/aptly/pull/577

Added documentation for notautomatic and butautomaticupgrades flags

---

content/doc/api/publish.md
content/doc/aptly/publish/drop.md
content/doc/aptly/publish/switch.md
content/doc/aptly/publish/update.md

Document new `-skip-cleanup` option

---

content/doc/aptly/publish/repo.md
content/doc/aptly/publish/snapshot.md

Adds documentation for https://github.com/smira/aptly/pull/664

Document new option acquire by hash

---

content/doc/integrations.md

Add link to python aptly GUI

---

content/doc/configuration.md
content/doc/feature/pgp-providers.md

make it clear that config files do not cascade / merge

---

content/doc/api/repos.md

See https://github.com/aptly-dev/aptly/pull/751

Document expose repo include in api

---

content/doc/api/snapshots.md

Documentation for creating a snapshot from a mirror is missing, this PR add it.

add documentation for creating mirrors snapshot

---

content/doc/api/publish.md

Fix: Remove Batch option from API

---

content/doc/api/snapshots.md

Related to: https://github.com/aptly-dev/aptly/pull/1157

Docs: Add Documentation for Merge Snapshots Feature

---

content/doc/api/mirror.md

See https://github.com/aptly-dev/aptly/pull/1300

Update mirror API documentation with async and force params

---

content/doc/api/publish.md

Document https://github.com/aptly-dev/aptly/pull/1292

document MultiDist flag

---

content/doc/api/repos.md

https://github.com/aptly-dev/aptly/pull/1375

Update create repo API docs to reflect changes made in [1375]

---

.github/workflows/gh-pages.yml

Fixes #94 
Does not run the deploy step unless for `master` branch. Also updated actions to latest versions.

Fix pr workflow
